
[item_drop]

	[item_drop.spooky]
		lucky_hoof = true
		phantom_rod = true
		deep_sea_orb = true

	[item_drop.global]
		shredder = true

[trophy_fishing]
	moldfin = 1
	blobfish = 0
	mana_ray = 1
	skeleton_fish = 1
	slugfish = 1
	volcanic_stonefish = 1
	flyfish = 1
	golden_fish = 1
	soul_fish = 1
	karate_fish = 1
	trophy_notification = false
	sulphur_skitter = 0
	obfuscated_2 = 0
	obfuscated_1 = 0
	gusher = 0
	steaming-hot_flounder = 1
	vanille = 1
	obfuscated_3 = 1
	lavahorse = 0

	[trophy_fishing.notification]
		rare_trophy_fish = true
		common_trophy_fish = true

	[trophy_fishing.rarity_selection]
		moldfin = 1
		blobfish = 0
		mana_ray = 1
		skeleton_fish = 1
		slugfish = 1
		volcanic_stonefish = 1
		flyfish = 1
		golden_fish = 1
		soul_fish = 1
		karate_fish = 1
		trophy_notification = true
		sulphur_skitter = 0
		obfuscated_2 = 0
		obfuscated_1 = 0
		gusher = 0
		steaming-hot_flounder = 1
		vanille = 1
		obfuscated_3 = 1
		lavahorse = 0

[pet_drop]

	[pet_drop.marina]
		megalodon = true
		legendary_megalodon = true
		epic_megalodon = true

	[pet_drop.global]
		flying_fish = true
		legendary_flying_fish = true
		rare_flying_fish = true
		epic_flying_fish = true

	[pet_drop.jerry]
		epic_baby_yeti = true
		legendary_baby_yeti = true
		baby_yeti = true

